#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

PS1=' $(tput setaf 246)\w$(tput sgr0)
  \$$(tput setaf 246)_$(tput sgr0) '

alias ls='ls --color=auto'

[ -f $HOME/.aliases ] && source $HOME/.aliases


[ -f ~/.fzf.bash ] && source ~/.fzf.bash
